# Generated by Django 4.1.5 on 2023-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0002_subscriptionplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
